// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.4"
#define MICROPY_GIT_HASH "421b84af"
#define MICROPY_BUILD_DATE "2018-07-30"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (4)
#define MICROPY_VERSION_STRING "1.9.4"
